In [31]:
import pandas as pd

# Open and drop empty answers

In [ ]:
# open results csv file

results = pd.read_csv('results_processed.csv')
results.head()

# # if rating column is empty, delete row
results = results.dropna(subset=['score'])

# save results to csv
results.to_csv('results_processed.csv', index=False)

### Combine participants and results_processed dataframes

In [32]:
# Combine participants and results_processed dataframes

participants = pd.read_csv('participants.csv')

# merge dataframes
merged = pd.merge(participants, results, on='participant_id')

# save merged dataframe to csv
merged.to_csv('merged.csv', index=False)

### Combine merged dataframes with the the tts atributes dataframe

In [18]:
merged = pd.read_csv('merged.csv')
merged.head()

,participant_id,age,gender,country,province,education,headphone_brand,stimuli,score,stimuli_group
0,5fiqr8ma74n55dce4kct9f,25,M,AR,NaN,2,NaN,E/E2/arf_00610_01166860348.wav,1.0,E2
1,0om1fva4uhily4cvg6368lr,22,M,AR,NaN,3,NaN,C/C7/conchita2_89.wav,2.0,C7
2,0om1fva4uhily4cvg6368lr,22,M,AR,NaN,3,NaN,E/E6/es-AR-ElenaNeural28.wav,3.0,E6
3,0om1fva4uhily4cvg6368lr,22,M,AR,NaN,3,NaN,D/D9/priscilla_76.wav,3.0,D9
4,0om1fva4uhily4cvg6368lr,22,M,AR,NaN,3,NaN,B/B1/audio70.wav,2.0,B1

In [19]:
# add stimuli group to merged dataframe

stimuli_group = []

# read the stimuli code in the merged dataframe
for item in merged['stimuli']:
    stimuli_group.append(item.split('/')[1])

# add stimuli group to merged dataframe
merged['stimuli_group'] = stimuli_group

# save merged dataframe to csv

merged.to_csv('merged.csv', index=False)

In [21]:
tts_atributes = pd.read_csv('tts_atributes.csv')

# merge dataframes

merged_final = pd.merge(merged, tts_atributes, on='stimuli_group')

# save merged_final dataframe to csv

merged_final.to_csv('merged_final.csv', index=False)
merged_final.head()

,participant_id,age,gender_x,country,province,education,headphone_brand,stimuli_x,score,stimuli_group,stimuli_y,gender_y,dialect
0,5fiqr8ma74n55dce4kct9f,25,M,AR,NaN,2,NaN,E/E2/arf_00610_01166860348.wav,1.0,E2,open_srl_es_ar_female_2,F,ARG
1,ymxfxn696we9rp1tnnub3f,26,P,AR,Buenos Aires,5,samsung,E/E2/arf_00610_00913913795.wav,5.0,E2,open_srl_es_ar_female_2,F,ARG
2,ymxfxn696we9rp1tnnub3f,26,P,AR,Buenos Aires,5,samsung,E/E2/arf_00610_00546762557.wav,5.0,E2,open_srl_es_ar_female_2,F,ARG
3,9fig36z1cml41m265ckifw,25,M,AR,Buenos Aires,4,Sony,E/E2/arf_00610_00621699750.wav,5.0,E2,open_srl_es_ar_female_2,F,ARG
4,vj735xlt2yj805wyn5rimq,59,F,AR,Buenos Aires,2,NaN,E/E2/arf_00610_00912390302.wav,4.0,E2,open_srl_es_ar_female_2,F,ARG